spring:
  application:
    name: PAMicroservice

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://45.153.190.237:5432/default_dbPA
    username: defaultPA
    password: Mm6347455627.
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual

minio:
  url: http://45.153.190.237:9000
  accessKey: OoB06v6642p0bikPNzHo
  secretKey: MZTGkDoFOFW94xR6vNQiLiukU5rOD0CMN7vqGbQq
  bucketName: photos

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
